server:
    port: 80
#if you don't use specific in manifest.yml as env variable, then you should specific below:
#spring:
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://github.com/spring-cloud-samples/config-repo
